### PR TITLE
feat: add metrics for request length and response length

### PR DESCRIPTION
**Pull request by matsumana**
Hi,
I would like to add the new metrics for Request length and Response length.

Motivation:
If an API handles a large JSON in request or response, the latency might get worse.
So I would like to monitor them.

### CODE REVIEW

**Comment by matsumana** [comment]
@joao-fontenele Could you take a look this PR?

**Review by joao-fontenele — CHANGES_REQUESTED** [review]
Hello @matsumana 

These are nice to have metrics, The only problem I see with this is making collecting it mandatory. If you make these changes optional, It would be good to merge

**Comment by matsumana** [comment]
Thank you for reviewing.
I have updated.

**Comment by matsumana** [comment]
@joao-fontenele Could you take a look this again?

**Comment by matsumana** [comment]
@joao-fontenele I am sorry to bother you. Could you take a look this again?

**Review by joao-fontenele-daitan — APPROVED** [review]
LGTM

**Comment by joao-fontenele** [comment]
@matsumana there's a conflict with master, if you resolve the conflicts I can merge it

**Comment by matsumana** [comment]
@joao-fontenele I could not find any conflicts.
According to the following message, seems there is no conflicts.

> This branch has no conflicts with the base branch

**Comment by joao-fontenele** [comment]
yep, my bad I was selecting the option to rebase and merge, and was seeing a conflict, but it's updated actually updated

**Comment by matsumana** [comment]
Thank you for reviewing.
Since I would like to use this feature, I would appreciate if you could release the new version.

**Comment by joao-fontenele** [comment]
@matsumana sorry for the delay, man, and thanks for the contribution.

Already released the new version

**Comment by matsumana** [comment]
Thank you so much!

**Pull request merged**
